### PR TITLE
Modernize codebase

### PR DESCRIPTION
**Pull request by Martchus**
See the particular commit messages for details, here's a short summary:

* There shouldn't be any functional changes.
* Most importantly, it works now with Qt 6 and as native Wayland application. (Of course Qt 5 should still work and is still the default.)
* When turning on warnings as "usual" when writing C++ I've noticed that there are tons of them in this code base. In order to be able to make use of compiler warnings in the future (instead of just being overwhelmed by them) I've fixed many warnings.
* I've been testing this manually and it seems to work.

### CODE REVIEW

**Comment by Martchus** [comment]
Looks like I need to make the use of new FluidSynth functions conditional. However, it looks like

```
[ 76%] Building CXX object build/CMakeFiles/pianobooster.dir/StavePosition.o
/home/runner/work/PianoBooster/PianoBooster/src/MidiDeviceFluidSynth.cpp: In member function ‘virtual bool CMidiDeviceFluidSynth::openMidiPort(CMidiDeviceBase::midiType_t, QString)’:
/home/runner/work/PianoBooster/PianoBooster/src/MidiDeviceFluidSynth.cpp:127:79: error: invalid conversion from ‘void (*)(void*, const char*, int)’ to ‘fluid_settings_foreach_t {aka void (*)(void*, char*, int)}’ [-fpermissive]
         fluid_settings_foreach(m_fluidSettings, 0, debug_settings_foreach_func);
                                                                               ^
In file included from /usr/include/fluidsynth.h:91:0,
                 from /home/runner/work/PianoBooster/PianoBooster/src/MidiDeviceFluidSynth.h:34,
                 from /home/runner/work/PianoBooster/PianoBooster/src/MidiDeviceFluidSynth.cpp:29:
/usr/include/fluidsynth/settings.h:213:6: note:   initializing argument 3 of ‘void fluid_settings_foreach(fluid_settings_t*, void*, fluid_settings_foreach_t)’
 void fluid_settings_foreach(fluid_settings_t* settings, void* data,
      ^~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [build/CMakeFiles/pianobooster.dir/MidiDeviceFluidSynth.o] Error 1
```

is also occurring on other PR, e.g. https://github.com/pianobooster/PianoBooster/pull/303.

**Comment by Martchus** [comment]
I've been adding a few changes to restore compatibility with older versions of FluidSynth and GCC but still retaining usages of newer APIs if available. Note that the fix https://github.com/pianobooster/PianoBooster/pull/317/commits/d32e11e743c72b65042c5bcfc3198ef8129da3b0 is actually required to get the Linux-CI build working again *independently* of my prior commits. So you may want to cherry pick this commit.

Maybe it is generally a good idea if you simply cherry pick commits from here as wanted in case you don't like all of it. I'll likely add further commits to this branch in the future to improve the project in the way *I* think it is best because it doesn't seem this project is maintained actively enough to have a dialog about the development. If my changes cannot be merged eventually this branch will unfortunately become a "fork".

**Comment by captnfab** [comment]
Hi @Martchus thanks for all this work!
@louis-barman, do you have some time to review/cherry-pick those changes?
If not, I can have a look at it.

**Comment by captnfab** [comment]
So, I'll have a look this week, I'll probably cherry-pick to merge-requests, and merge them when they seem ok to me.

**Comment by Martchus** [comment]
Thanks for accepting so many of my commits.I will rebase soon to see what's left.

**Comment by captnfab** [comment]
I changed the order of your commits (see #318, #319, #320, #321, #322 and #323), and added some more to make the CI happy, but I think I merged the whole branch eventually.
You did a great job with both the compatibility stuffs and the *use the right types* stuffs.
Many thanks, this project needed love!

I bumped the CI for linux to use ubuntu 20.04 for Qt5 and ubuntu 22.04 for Qt6. On MacOS X, version used is not 10.15 anymore, but 11, and the build uses Qt6 too. I added some instructions for building the Qt6 version on Ubuntu.

I'm planing on doing a release in a couple of days, unless you think some other things should be fixed before that.

**Comment by Martchus** [comment]
I've realized that everything is there when rebasing. One of the commits conflicted due to the changed order but it seems you have taken it over correctly.

Nice that you've improved the CI. It is good to test the Qt 6 builds as well. Considering Qt 6 lost support for older versions of certain platforms it is good to still have Qt 5 as well, though.

The only problem which comes to my mind (to sort out before releasing) is "not so nice" rendering of note names. I've just re-discovered this feature myself and the font rendering didn't look very nice. Maybe that's a regression of my changes or it was always like this.

**Comment by captnfab** [comment]
Indeed, display of Do/Ré/Mi/Fa/Sol/La/Si notes is broken (all letters are superimposed), but it was already broken in 1.0.0, so it's not because of your changes. I've seen some bugs from windows users too, I'll see if I can get the CI to build a windows version to be able to reproduce them (not sure how @louis-barman used to build the windows versions).

**Comment by Martchus** [comment]
Right, the problem about the menu bar in the Windows version. I didn't mention it because it was definitely broken before my changes. However, I'd also like to build this for Windows at some point. I'd personally would use the mingw-w64 packages on Arch Linux (and possibly fix some rough edges one might run into when cross-compiling). Supposedly MSYS2 is also an option, or even MSVC.

**Pull request closed without merging**
